apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-note
  annotations:
    # 本番環境用の設定
    alb.ingress.kubernetes.io/group.name: baseport-prd
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:674582907715:certificate/1fe9b416-1ccf-42b6-b77f-3e187e56edb1
    alb.ingress.kubernetes.io/security-groups: sg-04281baca92611c79
spec:
  rules:
    - host: fast-note.prd.baseport.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-note
                port:
                  number: 80
