apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fast-note-prod

resources:
  - ../../base

# すべてのリソースにprod-プレフィックスを追加
namePrefix: prod-

labels:
  - includeSelectors: true
    pairs:
      environment: prod

# レプリカ数を本番環境用に調整
replicas:
  - name: fast-note
    count: 1

# イメージタグを指定
images:
  # https://github.com/ng3rdstmadgke?tab=packages
  - name: fast-note
    newName: ghcr.io/ng3rdstmadgke/fast-note
    newTag: v1.0.2

# 本番環境用のパッチ
patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml

# ConfigMapの上書き
configMapGenerator:
  - name: fast-note-config
    behavior: merge
    literals:
      - NODE_ENV=production
