apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-note
  annotations:
    # 開発環境用の設定（baseport-expグループを使用）
    alb.ingress.kubernetes.io/group.name: baseport-exp
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:674582907715:certificate/919d1ab9-d21a-44ba-ab0c-f0dc387084f2
    alb.ingress.kubernetes.io/security-groups: sg-0b5b49f22a121de8c
spec:
  rules:
    - host: fast-note.prd-exp.baseport.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-note
                port:
                  number: 80
